#!/usr/bin/env node

const program = require('commander');
const GitTokenSigner = require('gittoken-signer').default;

program
	.option('-i, --init', 'Initialize New GitToken Signer')
  .option('-s, --socket <Socket Path>', 'Signer Socket Path')
  .option('-w3 --web3 <Web3 HTTP Provider>', 'Ethereum Web3 Provider')
	.option('-d --dir <Directory Path>', 'Directory to Save Keystore')
	.parse(process.argv);

if (!program.web3 || !program.dir) {
	console.log('Invalid Options')
	process.exit(1)
}

const signer = new GitTokenSigner({
	signerIpcPath: program.socket,
	recover: program.init != true,
	dirPath: program.dir,
	web3Provider: program.web3
})
